baseURL = 'https://diary.geekodour.org/'
languageCode = 'en-us'
title = 'diary ğŸ¤'
[module]
  [[module.imports]]
     path = "github.com/bake/solar-theme-hugo"
[markup.goldmark.renderer]
  unsafe = true
[menu]
  [[menu.main]]
    identifier = "travel"
    name = "Travel"
    title = "Travel"
    url = "/travel/"
    weight = 0
  [[menu.main]]
    identifier = "journal"
    name = "Journal"
    title = "Journal"
    url = "/journal/"
    weight = 1
  [[menu.main]]
    identifier = "homepage"
    name = "ğŸƒ"
    title = "ğŸƒ"
    url = "https://geekodour.org"
    weight = 0
[Params]
  custom_css = ["css/custom.css"]
