baseURL = 'https://diary.geekodour.org/'
languageCode = 'en-us'
title = 'diary ğŸ¤'
[module]
  [[module.imports]]
     path = "github.com/bake/solar-theme-hugo"
[markup.goldmark.renderer]
  unsafe = true
[menu]
  [[menu.main]]
    identifier = "travel"
    name = "Travel"
    title = "Travel"
    url = "/travel/"
    weight = 0
  [[menu.main]]
    identifier = "journal"
    name = "Journal"
    title = "Journal"
    url = "/journal/"
    weight = 0
