baseURL = 'https://diary.geekodour.org/'
languageCode = 'en-us'
title = 'diary ğŸ¤'
[module]
  [[module.imports]]
     path = "github.com/EmielH/tale-hugo"
[markup.goldmark.renderer]
  unsafe = true


